halo:
  halo_tag: ''
  fn_halo_config: ../configs/halos_TNG100-1.yaml
geo:
  geo_tag: ''
  fn_geo_config: ../configs/geo_TNG100-1.yaml
geo_clean:
  geo_clean_tag: _n3
  fn_geo_clean_features: ../data/geometric_features/geometric_features_clean_TNG100-1_n3.fits
  fn_geo_clean_info: ../data/geometric_features/geometric_info_clean_TNG100-1_n3.fits
  n_groups_rebin:
  - - 0
  - - 1
    - 2
    - 3
  - - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  mrv_names_for_rescaling:
  - m200m_fof
  - r200m
  - v200m_fof
  transform_pseudotensors: true
